// Generated by https://quicktype.io

export interface UserRequest {
    userName: string;
    password: string;
}


// Generated by https://quicktype.io

export interface UserAuthenticated {
    token:           string;
    tokenType:       string;
    rolePermissions: RolePermission[];
}

export interface RolePermission {
    roleDto:     RoleDto;
    permissions: Permission[];
}

export interface Permission {
    permissionId:   number;
    permissionName: string;
}

export interface RoleDto {
    roleId:   number;
    roleName: string;
}

